@StarWarsWebApplication_HostAddress = https://localhost:7206

GET {{StarWarsWebApplication_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{StarWarsWebApplication_HostAddress}}/weatherforecast

###
